insert into CATEGORIES (ID_CATEGORY, NAME) values (1, 'Artificial Intelligence');
insert into CATEGORIES (ID_CATEGORY, NAME) values (2, 'Artificial Intelligence');
insert into CATEGORIES (ID_CATEGORY, NAME) values (3, 'Internet of Things');
insert into CATEGORIES (ID_CATEGORY, NAME) values (4, 'Cybersecurity');
insert into CATEGORIES (ID_CATEGORY, NAME) values (5, 'Artificial Intelligence');
insert into CATEGORIES (ID_CATEGORY, NAME) values (6, 'Augmented Reality');
insert into CATEGORIES (ID_CATEGORY, NAME) values (7, 'Biotechnology');
insert into CATEGORIES (ID_CATEGORY, NAME) values (8, 'Cloud Computing');
insert into CATEGORIES (ID_CATEGORY, NAME) values (9, 'Biotechnology');
insert into CATEGORIES (ID_CATEGORY, NAME) values (10, 'Cybersecurity');
